name = "spmv"
version = "0.1.0"
license = "license"
author = "Jean-Christophe"
maintainer = "loiseau.jc@gmail.com"
copyright = "Copyright 2025, Jean-Christophe"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false
test = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[dependencies]
stdlib       = "*"
blas         = "*"
LightKrylov  = {git="https://github.com/nekStab/LightKrylov.git"}
forbenchmark = {git="https://github.com/gha3mi/forbenchmark.git"}
