name = "laplace"
version = "0.1.0"
license = "license"
author = "Jean-Christophe"
maintainer = "loiseau.jc@gmail.com"
copyright = "Copyright 2026, Jean-Christophe"

[build]
auto-executables = true
auto-tests = true
auto-examples = true
module-naming = false

[install]
library = false
test = false

[fortran]
implicit-typing = true
implicit-external = true
source-form = "free"

[dependencies]
stdlib      = "*"
# mpi         = "*"
LightKrylov = {git="https://github.com/nekStab/LightKrylov.git"}
